pipeline:
  test:
    image: jrei/crystal-alpine
    commands:
      - crystal spec
    when:
      branch: [master]

  docker-publish:
    image: plugins/docker
    repo: omerxx/drone-coralogix-version-plugin
    tags: 
      - latest
      - ${DRONE_BUILD_NUMBER}
    secrets: [ docker_username, docker_password ]
    when:
      branch: [master]
      event: push

