pipeline:
  test:
    image: jrei/crystal-alpine
    commands:
      - crystal spec
      - crystal build src/run.cr --release
    when:
      branch: [master, alpine]

  docker-publish:
    image: plugins/docker
    repo: omerxx/drone-coralogix-version-plugin
    tags: 
      - alpine
      - ${DRONE_BUILD_NUMBER}
    secrets: [ docker_username, docker_password ]
    when:
      branch: [master, alpine]
      event: push

